// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_units.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllBusinessUnitsInTenant = `-- name: GetAllBusinessUnitsInTenant :many
SELECT 
    id,
    domain_name,
    tenant_id,
    name,
    status,
    created_at,
    updated_at,
    deleted_at
FROM business_units 
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllBusinessUnitsInTenant(ctx context.Context, tenantID string) ([]BusinessUnit, error) {
	rows, err := q.db.Query(ctx, getAllBusinessUnitsInTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessUnit
	for rows.Next() {
		var i BusinessUnit
		if err := rows.Scan(
			&i.ID,
			&i.DomainName,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDepartmentsInBusinessUnit = `-- name: GetAllDepartmentsInBusinessUnit :many
SELECT 
    id,
    business_unit_id,
    name,
    status,
    created_at,
    updated_at,
    deleted_at
FROM departments 
WHERE business_unit_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllDepartmentsInBusinessUnit(ctx context.Context, businessUnitID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, getAllDepartmentsInBusinessUnit, businessUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.BusinessUnitID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBusinessUnitByDomainName = `-- name: GetBusinessUnitByDomainName :one
SELECT 
    id,
    domain_name,
    tenant_id,
    name,
    status,
    created_at,
    updated_at,
    deleted_at
FROM business_units 
WHERE domain_name = $1
`

func (q *Queries) GetBusinessUnitByDomainName(ctx context.Context, domainName string) (BusinessUnit, error) {
	row := q.db.QueryRow(ctx, getBusinessUnitByDomainName, domainName)
	var i BusinessUnit
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessUnitByID = `-- name: GetBusinessUnitByID :one
SELECT 
    id,
    domain_name,
    tenant_id,
    name,
    status,
    created_at,
    updated_at,
    deleted_at
FROM business_units 
WHERE id = $1
`

func (q *Queries) GetBusinessUnitByID(ctx context.Context, id pgtype.UUID) (BusinessUnit, error) {
	row := q.db.QueryRow(ctx, getBusinessUnitByID, id)
	var i BusinessUnit
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
