// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BusinessUnit struct {
	ID         pgtype.UUID        `json:"id"`
	DomainName string             `json:"domain_name"`
	TenantID   string             `json:"tenant_id"`
	Name       string             `json:"name"`
	IsActive   pgtype.Bool        `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID             pgtype.UUID        `json:"id"`
	BusinessUnitID pgtype.UUID        `json:"business_unit_id"`
	Name           string             `json:"name"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	AzureAdObjectID string             `json:"azure_ad_object_id"`
	HomeTenantID    pgtype.UUID        `json:"home_tenant_id"`
	DepartmentID    pgtype.UUID        `json:"department_id"`
	ManagerID       pgtype.UUID        `json:"manager_id"`
	Mail            string             `json:"mail"`
	DisplayName     string             `json:"display_name"`
	GivenName       pgtype.Text        `json:"given_name"`
	SurName         pgtype.Text        `json:"sur_name"`
	JobTitle        pgtype.Text        `json:"job_title"`
	OfficeLocation  pgtype.Text        `json:"office_location"`
	IsActive        pgtype.Bool        `json:"is_active"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
