// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllBusinessUnitsInTenant(ctx context.Context, tenantID string) ([]BusinessUnit, error)
	GetAllDepartmentsInBusinessUnit(ctx context.Context, businessUnitID pgtype.UUID) ([]Department, error)
	GetAllUsersInDepartment(ctx context.Context, departmentID pgtype.UUID) ([]User, error)
	GetBusinessUnitByDomainName(ctx context.Context, domainName string) (BusinessUnit, error)
	GetBusinessUnitByID(ctx context.Context, id pgtype.UUID) (BusinessUnit, error)
	GetDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error)
	GetDepartmentByName(ctx context.Context, arg GetDepartmentByNameParams) (Department, error)
	GetUserByEmail(ctx context.Context, mail string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
