// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scopes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScope = `-- name: CreateScope :one
INSERT INTO scopes (
    id,
    name,
    description,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, description, status, created_at, updated_at, deleted_at
`

type CreateScopeParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Status      NullStatusEnum `json:"status"`
}

func (q *Queries) CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, createScope,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllScopes = `-- name: GetAllScopes :many
SELECT 
    id,
    name,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM scopes 
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) GetAllScopes(ctx context.Context) ([]Scope, error) {
	rows, err := q.db.Query(ctx, getAllScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scope
	for rows.Next() {
		var i Scope
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeByID = `-- name: GetScopeByID :one
SELECT 
    id,
    name,
    description,
    status,
    created_at,
    updated_at,
    deleted_at
FROM scopes 
WHERE id = $1
`

func (q *Queries) GetScopeByID(ctx context.Context, id string) (Scope, error) {
	row := q.db.QueryRow(ctx, getScopeByID, id)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
