name: Coverity Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverity:
    name: Run Coverity Scan
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Clear Go cache
        run: |
          go clean -cache -modcache -testcache
          rm -rf ~/go/pkg/mod

      - name: Verify Go version
        run: go version

      # Cache coverity_tool to save bandwidth/time
      - name: Cache Coverity Tool
        id: cache-coverity-tool
        uses: actions/cache@v3
        with:
          path: coverity_tool
          key: coverity-tool-${{ runner.os }}-${{ secrets.COVERITY_TOKEN }}
          restore-keys: |
            coverity-tool-${{ runner.os }}-

      - name: Download Coverity Tool if not cached
        if: steps.cache-coverity-tool.outputs.cache-hit != 'true'
        run: |
          mkdir -p coverity_tool
          wget --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ secrets.COVERITY_PROJECT_NAME }}" \
               https://scan.coverity.com/download/linux64 \
               -O coverity_tool/coverity_tool.tgz
          tar xzf coverity_tool/coverity_tool.tgz -C coverity_tool
          echo "COVERITY_DIR=$(find coverity_tool -maxdepth 1 -type d -name 'cov-analysis*')" >> $GITHUB_ENV

      - name: Configure Coverity for Go
        run: |
          $COVERITY_DIR/bin/cov-configure --template --compiler go --comptype go

      - name: Run cov-build
        run: |
          mkdir cov-int
          # $COVERITY_DIR/bin/cov-build --dir cov-int go build ./...
          $COVERITY_DIR/bin/cov-build --dir cov-int go build -mod=mod ./cmd/...

      - name: Check cov-int contents
        run: |
          echo "Listing cov-int contents:"
          ls -R cov-int

      - name: Package results
        run: tar czf analysis.tgz cov-int

      - name: Upload to Coverity Scan
        run: |
          curl --form token=${{ secrets.COVERITY_TOKEN }} \
               --form email=${{ secrets.COVERITY_EMAIL }} \
               --form file=@analysis.tgz \
               --form version="GitHub Action Build $GITHUB_RUN_NUMBER" \
               --form description="Automated scan from GitHub Actions" \
               https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT_NAME }}
