name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.12
        with:
          token: ${{ secrets.SONAR_CLOUD_TOKEN }}
          projectKey: BLuBinn_yet-another-itsm
          organization: Blubinn
          args: >
            -Dsonar.go.build-wrapper-output=build-wrapper-output
            -Dsonar.go.tests=true
            -Dsonar.go.coverage.reportPaths=coverage.out
