name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/sonarcloud-analysis
        with:
          sonar-token: ${{ secrets.SONAR_CLOUD_TOKEN }}
