name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/actions/action.yaml
        with:
          sonar-token: ${{ secrets.SONAR_CLOUD_TOKEN }}
